### ISSUE TITLE
Eval: Some classes output NaN because of Npos=0

### ISSUE THREAD

**Issue by ishitamed19** [zeliu98/Group-Free-3D#12]
Hi!
I am trying to evaluate on all Scannet classes (485). Since some classes are very rare, running the `eval_det_cls` for them throws `NaN` because of `npos=0`. Can you recommend a fix for this?

**Comment by stupidZZ** [comment]
We did not try to evaluate all Scannet classes as you did, but according to your description, maybe you can change the evaluation code (eval_det.py#L164) from:

`    rec = tp / float(npos)` .

to 

 `    rec = tp / (float(npos) + 1e-5)` .


Hope it will help you.
