### ISSUE TITLE
Visualizations on cross-attention weight in different decoder stages

### ISSUE THREAD

**Issue by jlqzzz** [zeliu98/Group-Free-3D#3]
Dear author, 
Thank you for your good work. 
I want to know how to visualize the results in Figure 5. Can you provide the corresponding visualization code?

**Comment by zeliu98** [comment]
Hi, I use [open3d](https://github.com/intel-isl/Open3D) to visualize it, by setting different colors to points according to the attention weight.

**Comment by abhigoku10** [comment]
@zeliu98  can you please share ur code for visualization it will be helpful 
Thanks in advance
