### ISSUE TITLE
Loss become nan when at about 300 epoch

### ISSUE THREAD

**Issue by adrien-Chen** [zeliu98/Group-Free-3D#8]
Thanks for your excellent work! 

I encountered a  problem during the training.
Since I only have one GPU, so I modified the train_dist.py to a single GPU version (just remove the codes about distribution).
![Screenshot from 2021-05-11 09-31-19](https://user-images.githubusercontent.com/22374844/117744713-cd2c9e00-b23b-11eb-93d5-46dadfac9c84.png)

I want to know if is there anything else needs to be modified? And if you have any suggestion about this problem? Thanks very much!!

**Comment by xiyuchenji** [comment]
> Thanks for your excellent work!
> 
> I encountered a problem during the training.
> Since I only have one GPU, so I modified the train_dist.py to a single GPU version (just remove the codes about distribution).
> ![Screenshot from 2021-05-11 09-31-19](https://user-images.githubusercontent.com/22374844/117744713-cd2c9e00-b23b-11eb-93d5-46dadfac9c84.png)
> 
> I want to know if is there anything else needs to be modified? And if you have any suggestion about this problem? Thanks very much!!



> Thanks for your excellent work!
> 
> I encountered a problem during the training.
> Since I only have one GPU, so I modified the train_dist.py to a single GPU version (just remove the codes about distribution).
> ![Screenshot from 2021-05-11 09-31-19](https://user-images.githubusercontent.com/22374844/117744713-cd2c9e00-b23b-11eb-93d5-46dadfac9c84.png)
> 
> I want to know if is there anything else needs to be modified? And if you have any suggestion about this problem? Thanks very much!!
Hi, I want to run  this code on  a single GPU, but I met some mistakes.Can you tell how to modify this code to run in a single GPU? I' m looking forward your reply.
